# Generated by Django 3.1.2 on 2024-10-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='board',
            name='price',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='board',
            name='region',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='board',
            name='seller',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='board',
            name='serial',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='board',
            name='date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='board',
            name='text',
            field=models.TextField(default=None),
        ),
    ]
